### PR TITLE
Updates related to Attributes

### PR DESCRIPTION
**Pull request by umarcor**
# New Features
* Improved and tested attributes to entities in the ProjectModel (on project, design, fileset and file).

# Changes
* Bumped dependencies.
* Adjusted file headers.
* Added module doc-strings.

# Bug Fixes
*None*

### CODE REVIEW

**Comment by umarcor** [comment]
@Paebbels, did you drop the 8 commits from this branch on purpose?

**Comment by Paebbels** [comment]
Argh fuck, what happend here.

**Comment by Paebbels** [comment]
@umarcor I can't rescue that branch from my side. This branch was rebased on your side, so you're local copy is the only one having references. You need to repush it. I'll rename the current `paebbels/dev` branch to `paebbels/dev2`. Then the original name can be used again. Either the repush opens this PR again or it needs a manual reopen.

--------
I now remember that I had problems fast-forwarding that branch even on a straight forward path. It was quite strange ...

This is why others should never touch private branches (`<user>/<branch>`) without previous agreement on such a change like a rebase.

--------
Moreover GitHub doesn't offer any option to rescue such a branch by:
* restoring the deleted branch
* adding a tag
* adding a new branch name

**Comment by Paebbels** [comment]
OK, after freeing up the branch name (I now used `paebbels/testcases`, I could click on restore branch for the PR.

**Comment by umarcor** [comment]
> Argh fuck, what happend here.

- There were some commits in branch `dev`.
- You had pushed these 8 commit to branch `dev` directly.
- I wanted to add more commits to branch `dev`, but CI was failing, because some of the 8 commits are WIP and are not complete.

What I did was:

- Rename "your" `dev` branch to `paebbels/dev`.
- Revert `dev` to before the 8 commits.
- Create my additional commits in branch `umarcor/dev`.
- Open a PR for `paebbels/dev` (this one) and another PR for `umarcor/dev` (#39), both of them targeting `dev`.

What I think happened later is:

- You created a local `paebbels/dev` without realising that it existed in the remote.
- Then, force-pushed thinking that whatever was in the remote was old, instead of new.

Anyway, I had kept a local copy of `paebbels/dev` as a backup, because this could happen.

> Moreover GitHub doesn't offer any option to rescue such a branch by

It does not, and it is really annoying. In other situations, I "lost" commits/branches which are still shown in GitHub, but which are not accessible through `git`. It seems that the `bare` copy of the repo in the server can contain old references but they are not readable. That's why I kept a local copy, just in case. It's fortunate that it allowed to reopen the PR.

> This is why others should never touch private branches (<user>/<branch>) without previous agreement on such a change like a rebase.

I did not really modify the content of `paebbels/dev`; it did not exist. I renamed `dev` to `paebbels/dev` and then reverted `dev`. When fetching, git should have shown that your local `dev` was pointing exactly at the new remote `paebbels/dev`.

Anyway, now everything should be ok. We have one `dev` branch, one feature branch of mine and two feature branches of yours.

**Comment by Paebbels** [comment]
Branch is now fixed.

**Pull request merged**
