### PR TITLE
v0.4.1

### PR DESCRIPTION
**Pull request by umarcor**
# New Features

* Add VSCode settings.
* Add scheduled/cron CI event.

# Changes

* README: update heading levels.
* Setup: remove redundant classifiers.
* Update `.gitignore`.
* Cleanup `doc/Makefile`.
* Merge `.coveragerc` and `pytest.ini` into `pyproject.toml`.
* Added links to type check and coverage reports from documentation sidebar.
* Added many doc-strings.

# Bug Fixes

* Job ArtifactCleanUp in CI needs PublishTestResults.
* Fix linter warnings.
* Update Codacy target URLs, from `manual` to `gh`.

------------------
Integrated Pull Requests:
* #38 
* #39

### CODE REVIEW

**Comment by Paebbels** [comment]
@umarcor
* All sub-PRs are merged.
* Change log was adjusted.
* CI is successful.

**Comment by Paebbels** [comment]
@umarcor as you opened the PR, I can't request a review by you :(.

As we checked most items in the sub-PRs in our meeting, I'll go on and merge it.
I checked it myself 2x and fixed all open or discussed issues.

**Review by Paebbels — APPROVED** [review]

**Comment by umarcor** [comment]
@Paebbels, it seems that the changelog here and in https://github.com/edaa-org/pyEDAA.ProjectModel/releases is missing some of the items from #38?

**Comment by Paebbels** [comment]
I updated https://github.com/edaa-org/pyEDAA.ProjectModel/pull/37 and then the release notes.

**Root cause:**  
The items from sub-PR were not copied to the main PR for the v0.4.1 release.

**Pull request merged**
